name: Rust

on:
  push:
    branches: [ "master", "stable", "update-stable" ]
  pull_request:
    branches: [ "master", "stable", "update-stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
